# Generated by Django 6.1 on 2026-09-03 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspension",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("fraud", "Fraud"),
                            ("chargeback", "Chargeback"),
                            ("abuse", "Abuse"),
                            ("tos", "Terms of Service"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("suspended_at", models.DateTimeField(auto_now_add=True)),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_lifted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suspended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suspensions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-suspended_at"],
                "indexes": [models.Index(fields=["user", "-suspended_at"], name="administrat_user_id_b9678d_idx")],
            },
        ),
    ]
